### ISSUE TITLE
Using action scheduler in unit/integration tests

### ISSUE THREAD

**Issue by dingo-d** [Prospress/action-scheduler#1070]
Hi!

I'm wondering what would be the correct way to load action scheduler during automated tests?

I'm using [my own](https://github.com/dingo-d/wp-pest) package for integration testing, and my `bootstrap.php` file looks like this

```php
<?php

use Yoast\WPTestUtils\WPIntegration;

// Autoload everything for unit tests.
$ds = DIRECTORY_SEPARATOR;
require_once dirname(__FILE__, 2) . $ds . 'vendor' . $ds . 'autoload.php';

/**
 * Include core bootstrap for an integration test suite
 *
 * This will only work if you run the tests from the command line.
 * Running the tests from IDE such as PhpStorm will require you to
 * add additional argument to the test run command if you want to run
 * integration tests.
 */
if (isset($GLOBALS['argv']) && in_array('--group=integration', $GLOBALS['argv'], true)) {
	if (!file_exists(dirname(__FILE__, 2) . '/wp/tests/phpunit/wp-tests-config.php')) {
		// We need to set up core config details and test details
		copy(
			dirname(__FILE__, 2) . '/wp/wp-tests-config-sample.php',
			dirname(__FILE__, 2) . '/wp/tests/phpunit/wp-tests-config.php'
		);

		// Change certain constants from the test's config file.
		$testConfigPath = dirname(__FILE__, 2) . '/wp/tests/phpunit/wp-tests-config.php';
		$testConfigContents = file_get_contents($testConfigPath);

		$testConfigContents = str_replace(
			"dirname( __FILE__ ) . '/src/'",
			"dirname(__FILE__, 3) . '/src/'",
			$testConfigContents
		);
		$testConfigContents = str_replace("youremptytestdbnamehere", $_SERVER['DB_NAME'], $testConfigContents);
		$testConfigContents = str_replace("yourusernamehere", $_SERVER['DB_USER'], $testConfigContents);
		$testConfigContents = str_replace("yourpasswordhere", $_SERVER['DB_PASSWORD'], $testConfigContents);
		$testConfigContents = str_replace("localhost", $_SERVER['DB_HOST'], $testConfigContents);

		file_put_contents($testConfigPath, $testConfigContents);
	}

	// Give access to tests_add_filter() function.
	require_once dirname(__FILE__, 2) . '/wp/tests/phpunit/includes/functions.php';

	/**
	 * Manually load the plugin being tested.
	 */
	function _manually_load_plugin()
	{
		require dirname(__DIR__) . '/my-plugin.php';
		require dirname(__DIR__) . '/wp-content/plugins/action-scheduler/action-scheduler.php';
	}

	tests_add_filter('muplugins_loaded', '_manually_load_plugin');

	require_once dirname(__DIR__) . '/vendor/yoast/wp-test-utils/src/WPIntegration/bootstrap-functions.php';

	/*
	 * Bootstrap WordPress. This will also load the Composer autoload file, the PHPUnit Polyfills
	 * and the custom autoloader for the TestCase and the mock object classes.
	 */
	WPIntegration\bootstrap_it();
}
```

However, when I run my tests, I get the following error:

```bash
> @php ./vendor/bin/pest --group=integration
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
PHPUnit 9.6.19 by Sebastian Bergmann and contributors.

Error in bootstrap script: Whoops\Exception\ErrorException:
Function as_get_scheduled_actions was called incorrectly. as_get_scheduled_actions() was called before the Action Scheduler data store was initialized Please see <a>Debugging in WordPress</a> for more information. (This message was added in version 3.1.6.)
#0 [internal function]: Whoops\Run->handleError(1024, 'Function as_get...', '/Users/dzoljom/...', 6078)
#1 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/wp/src/wp-includes/functions.php(6078): trigger_error('Function as_get...', 1024)
#2 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/wp/src/wp-includes/functions.php(6022): wp_trigger_error('', 'Function as_get...')
#3 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/wp-content/plugins/action-scheduler/classes/abstracts/ActionScheduler.php(229): _doing_it_wrong('as_get_schedule...', 'Function as_get...', '(This message w...')
#4 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/wp-content/plugins/action-scheduler/functions.php(438): ActionScheduler::is_initialized('as_get_schedule...')
#5 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/src/Post/PostWatchService.php(23): as_get_scheduled_actions(Array)
#6 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/src/Post/PostWatchService.php(15): MyPlugin\Post\PostWatchService->getCallback()
#7 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/src/Core/Plugin.php(59): MyPlugin\Post\PostWatchService->register()
#8 [internal function]: MyPlugin\Core\Plugin::MyPlugin\Core\{closure}(Object(MyPlugin\Post\PostWatchService), 'MyPlugin...')
#9 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/src/Core/Plugin.php(55): array_walk(Array, Object(Closure))
#10 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/wp/src/wp-includes/class-wp-hook.php(324): MyPlugin\Core\Plugin->registerServices('')
#11 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/wp/src/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#12 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/wp/src/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#13 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/wp/src/wp-settings.php(550): do_action('plugins_loaded')
#14 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/wp/tests/phpunit/includes/bootstrap.php(305): require_once('/Users/dzoljom/...')
#15 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/yoast/wp-test-utils/src/WPIntegration/bootstrap-functions.php(172): require_once('/Users/dzoljom/...')
#16 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/yoast/wp-test-utils/src/WPIntegration/bootstrap-functions.php(130): Yoast\WPTestUtils\WPIntegration\load_wp_test_bootstrap()
#17 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/tests/bootstrap.php(64): Yoast\WPTestUtils\WPIntegration\bootstrap_it()
#18 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once('/Users/dzoljom/...')
#19 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/Users/dzoljom/...')
#20 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/TextUI/Command.php(567): PHPUnit\Util\FileLoader::checkAndLoad('/Users/dzoljom/...')
#21 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/TextUI/Command.php(347): PHPUnit\TextUI\Command->handleBootstrap('/Users/dzoljom/...')
#22 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/pestphp/pest/src/Console/Command.php(62): PHPUnit\TextUI\Command->handleArguments(Array)
#23 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/TextUI/Command.php(114): Pest\Console\Command->handleArguments(Array)
#24 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/pestphp/pest/src/Console/Command.php(119): PHPUnit\TextUI\Command->run(Array, false)
#25 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/pestphp/pest/bin/pest(62): Pest\Console\Command->run(Array)
#26 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/pestphp/pest/bin/pest(63): {closure}()
#27 /Users/dzoljom/Sites/test/wp-content/plugins/my-plugin/vendor/bin/pest(119): include('/Users/dzoljom/...')
#28 {main}
Script @php ./vendor/bin/pest --group=integration handling the test:integration event returned with error code 1
```

What I need to know is what would be the correct way to initialize the data store?

**Comment by dingo-d** [comment]
Ok, made it work (at least tests are passing)

```php
	/**
	 * Manually load the plugin dependencies.
	 */
	function _manually_load_dependencies()
	{
		require dirname(__DIR__) . '/wp-content/plugins/action-scheduler/action-scheduler.php';
	}

	/**
	 * Manually load the plugin being tested.
	 */
	function _manually_load_plugin()
	{
		require dirname(__DIR__) . '/my-plugin.php';
	}

	tests_add_filter('muplugins_loaded', '_manually_load_dependencies');
	tests_add_filter('plugins_loaded', '_manually_load_plugin');
```

Remembered I saw a note about loading order in the docs so I gave this a go.
