### ISSUE TITLE
Possible bug: Bulk delete from Scheduled Actions menu results in PHP errors

### ISSUE THREAD

**Issue by jonathanstegall** [Prospress/action-scheduler#200]
I didn't see an issue for this, so I thought I'd mention.

I'm not running WooCommerce, and I'm seeing this on a local environment (PHP 7.1, Nginx, Laravel Valet). I have `define( 'WP_DEBUG_LOG', true );` in wp-config.

>  Warning: Cannot modify header information - headers already sent by (output started at /wp-includes/class.wp-styles.php:225) in /wp-includes/pluggable.php on line 1219

This happens every time I try to check the boxes for multiple rows and delete them. If I try to reload the page on the same screen, without navigating elsewhere, I get this error:

>  Fatal error: Uncaught InvalidArgumentException: Unidentified action 162136 in (plugin path)/vendor/prospress/action-scheduler/classes/ActionScheduler_wpPostStore.php:407 Stack trace: #0 (plugin path)/vendor/prospress/action-scheduler/classes/ActionScheduler_ListTable.php(404): ActionScheduler_wpPostStore->delete_action('162136') #1 (plugin path)/vendor/prospress/action-scheduler/classes/ActionScheduler_Abstract_ListTable.php(151): ActionScheduler_ListTable->bulk_delete(Array, '('162136','1621...') #2 (plugin path)/vendor/prospress/action-scheduler/classes/ActionScheduler_ListTable.php(458): ActionScheduler_Abstract_ListTable->process_bulk_action() #3 (plugin path) in (plugin path)/vendor/prospress/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 407

If I click Scheduled Actions in the menu, instead of reloading, the page loads correctly and it has deleted the selected records.

I noticed this does not happen when I sort the table (by Hook, for example) but it does happen when I search for anything in the search box.

**Comment by jonathanstegall** [comment]
Nevermind, I think I see now this is a duplicate of #151
