### ISSUE TITLE
 PHP Fatal error Uncaught InvalidArgumentException: Unidentified action

### ISSUE THREAD

**Issue by alewolf** [Prospress/action-scheduler#970]
It seems that on some installs of our plugin, the fatal error ` PHP Fatal error Uncaught InvalidArgumentException: Unidentified action` is triggered. 

There is a similar report that wasn't resolved: https://github.com/woocommerce/action-scheduler/issues/882

Any idea what's causing this?

At least, could you add a safeguard not to let it run into a fatal error?

```
unexpected shutdown: PHP Fatal error Uncaught InvalidArgumentException: Unidentified action 2943442 in /www/example/public/wp-content/plugins/pixel-manager-pro-for-woocommerce/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:1075  
Stack trace:  
#0 /www/example/public/wp-content/plugins/pixel-manager-pro-for-woocommerce/vendor/woocommerce/action-scheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(120): ActionScheduler_DBStore->mark_failure(2943442)  
#1 /www/example/public/wp-content/plugins/pixel-manager-pro-for-woocommerce/vendor/woocommerce/action-scheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(98): ActionScheduler_Abstract_QueueRunner->handle_action_error(2943442, Object(Exception), 'Async Request', true)  
#2 /www/example/public/wp-content/plugins/pixel-manager-pro-for-woocommerce/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueRunner.php(166): ActionScheduler_Abstract_QueueRunner->process_action(2943442, 'Async Request')  
#3 /www/example/public/wp-content/plugins/pixel-manager-pro-for-woocommerce/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueRunner.php(136): ActionScheduler_QueueRunner->do_batch(25, 'Async Request')  
#4 /www/example/public/wp-includes/class-wp-hook.php(308): ActionScheduler_QueueRunner->run('Async Request') 
```

**Comment by barryhughes** [comment]
> Any idea what's causing this?

Well, really any of the same possibilities outlined in #882.

> Could you add a safeguard not to let it run into a fatal error?

Yes, I think we could do something [similar to this fix](https://github.com/woocommerce/action-scheduler/pull/964/files) (where bulk deletes could also result in a fatal, under certain circumstances).
